name: Tests

on:
    push:

jobs:
    tests:
        runs-on: docker
        container:
            image: ghcr.io/catthehacker/ubuntu:js-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: yarn install --frozen-lockfile --ignore-scripts

            - name: Check Types
              run: yarn typescript

            - name: Test ESLint
              run: yarn lint
